### ISSUE TITLE
Ящик возвращается

### ISSUE THREAD

**Issue by Ansfer90** [vitalexbel/Scrabble#164]
Когда предлагают слова, то вроде в последние разы ящик сразу не выбирался у игроков, которые должны выбрать "да" или "нет". То есть, ты предложил слово, а мне приходится искать ящик, чтобы выбрать, да или нет.

**Comment by vitalexbel** [comment]
я понял тебя. раньше тоже не было функции, чтобы он выбирался. я имею ввиду в этом эрудите. может, в старых версиях, которые я делал несколько лет назад, такое было

**Comment by vitalexbel** [comment]
ты хочешь, чтобы выбирался??? в принципе, логично... можно сделать

**Comment by Ansfer90** [comment]
да, тогда точно выбирался, я помню

**Comment by vitalexbel** [comment]
ок, сделаю, чтобы выбирался, у тех, кто голосует

**Comment by vitalexbel** [comment]
сделал. теперь, когда игрок будет голосовать, весь выбор будет сбрасываться и будет выбираться только контроллер
